server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/linking-test?serverTimezone=Asia/Seoul
    username: root
    password: 0881

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        jpa.compliance.proxy: false
        show_sql: false
        format_sql: true
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 100 #최적화 옵션
#        use_sql_comments: true



#hibernate:
#  discriminator:
#  ignore_explicit_for_joined=true:

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


# swaggerdoc
springdoc:
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    tags-sorter: method  # 알파벳 순 태그 정렬, method : HTTP Method 순 정렬
    operations-sorter: method
  cache:
    disabled: true
  packages-to-scan: com.linking
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
