server:
  port: 8080

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/linking-test?serverTimezone=Asia/Seoul
#    username: root
#    password: 0881
    url: jdbc:mysql://linking-mysql.c23kvlbmlqie.ap-northeast-2.rds.amazonaws.com:3306/linking?serverTimezone=Asia/Seoul
    username: saessack
    password: dmsqls0881

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        jpa.compliance.proxy: false
        show_sql: false
        format_sql: true
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 100 #최적화 옵션
#        order_updates: true
#        jdbc:
#          batch_size: 100
#        use_sql_comments: true



#hibernate:
#  discriminator:
#  ignore_explicit_for_joined=true:

logging:
  pattern:
    dateformat: YY-MM-dd HH:mm:ss,Asia/Seoul
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
